config/routes.rb
# config/routes.rb
Rails.application.routes.draw do
  resources :kittens
  get '/kittens/:id', to: 'kittens#show'
  # Set the default route to kittens#index
  root 'kittens#index'
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/kitten.rb
class Kitten < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/kittens_controller.rb
# app/controllers/kittens_controller.rb
class KittensController < ApplicationController
    before_action :set_kitten, only: [:show, :edit, :update, :destroy]
    
    # GET /kittens
    # GET /kittens.json
    def index
      @kittens = Kitten.all
      respond_to do |format|
        format.html
        format.json { render json: @kittens }
      end
    end
      
    # GET /kittens/1
    def show
      @kitten = Kitten.find(params[:id])
      render json: @kitten
    rescue ActiveRecord::RecordNotFound
      render json: { error: 'Kitten not found' }, status: :not_found
    end
    
    # GET /kittens/new
    def new
      @kitten = Kitten.new
    end
    
    # GET /kittens/1/edit
    def edit
    end
    
    # POST /kittens
    def create
      @kitten = Kitten.new(kitten_params)
  
      if @kitten.save
        flash[:notice] = 'Congratulations! You successfully added a kitten.'
        redirect_to @kitten
      else
        flash[:alert] = 'Oops! There were errors in your form.'
        render :new
      end
    end
    
    # PATCH/PUT /kittens/1
    def update
      if @kitten.update(kitten_params)
        flash[:notice] = 'Congratulations! You successfully updated the kitten.'
        redirect_to @kitten
      else
        flash[:alert] = 'Oops! There were errors in your form.'
        render :edit
      end
    end
    
    # DELETE /kittens/1
    def destroy
      @kitten.destroy
      flash[:notice] = 'Congratulations! You successfully deleted the kitten.'
      redirect_to kittens_url
    end
    
    private
    
    def set_kitten
      @kitten = Kitten.find(params[:id])
    end
    
    def kitten_params
      params.require(:kitten).permit(:name, :age, :cuteness, :softness)
    end
  end
  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/views/kittens/_form.html.erb
<!-- app/views/kittens/_form.html.erb -->
<%= form_with(model: kitten, local: true) do |form| %>
  <% if kitten.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(kitten.errors.count, "error") %> prohibited this kitten from being saved:</h2>

      <ul>
        <% kitten.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :age %>
    <%= form.number_field :age %>
  </div>

  <div class="field">
    <%= form.label :cuteness %>
    <%= form.number_field :cuteness %>
  </div>

  <div class="field">
    <%= form.label :softness %>
    <%= form.number_field :softness %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/kittens/edit.html.erb
<!-- app/views/kittens/edit.html.erb -->
<h1>Edit Kitten</h1>

<%= render 'form', kitten: @kitten %>

<%= link_to 'Back', kittens_path %> |
<%= link_to 'Destroy', @kitten, method: :delete, data: { confirm: 'Are you sure?' } %>

app/views/kittens/index.html.erb
<!-- app/views/kittens/index.html.erb -->
<h1>All Kittens</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
      <th>Cuteness</th>
      <th>Softness</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @kittens.each do |kitten| %>
      <tr>
        <td><%= kitten.name %></td>
        <td><%= kitten.age %></td>
        <td><%= kitten.cuteness %></td>
        <td><%= kitten.softness %></td>
        <td><%= link_to 'Show', kitten %></td>
        <td><%= link_to 'Edit', edit_kitten_path(kitten) %></td>
        <td><%= link_to 'Destroy', kitten, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New Kitten', new_kitten_path %>

app/views/kittens/new.html.erb
<!-- app/views/kittens/new.html.erb -->
<h1>New Kitten</h1>

<%= render 'form', kitten: @kitten %>

<%= link_to 'Back', kittens_path %>

app/views/kittens/show.html.erb
<!-- app/views/kittens/show.html.erb -->
<h1>Kitten Details</h1>

<p>
  <strong>Name:</strong>
  <%= @kitten.name %>
</p>
<p>
  <strong>Age:</strong>
  <%= @kitten.age %>
</p>
<p>
  <strong>Cuteness:</strong>
  <%= @kitten.cuteness %>
</p>
<p>
  <strong>Softness:</strong>
  <%= @kitten.softness %>
</p>

<%= link_to 'Edit', edit_kitten_path(@kitten) %> |
<%= link_to 'Back', kittens_path %> |
<%= link_to 'Destroy', @kitten, method: :delete, data: { confirm: 'Are you sure?' } %>

app/views/layouts/_flash_messages.html.erb
<!-- app/views/layouts/_flash_messages.html.erb -->
<% flash.each do |key, message| %>
  <div class="flash <%= key %>">
    <%= message %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!-- app/views/layouts/application.html.erb -->
<!DOCTYPE html>
<html>
<head>
  <title>KittenApp</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>


<body>
  <%= render 'layouts/flash_messages' %>
  <%= yield %>
</body>
</html>